version: '3'
services:
  jerex-api:
    build: ./
    stdin_open: true
    tty: true
    networks:
      - api
    ports:
      - 8080:8080
    command: ["uvicorn", "api_service:app", "--host", "0.0.0.0", "--port", "8080"]
    environment:
      NVIDIA_VISIBLE_DEVICES: 0
      CUDA_VISIBLE_DEVICES: 0
    ulimits:
      memlock: -1
    shm_size: '16gb'
    volumes:
      - .:/jerex
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  api: