dataset:
  test_path: ./data/datasets/docred_joint/1000_texts.csv
  # test_path: ./data/datasets/docred_joint/test_joint.json
  # test_path: ./data/datasets/docred_joint/test_documents.csv
  types_path: ./data/datasets/docred_joint/types.json

model:
  model_path: ./data/models/docred_joint/joint_multi_instance/model.ckpt #./data/models/docred_joint/joint_multi_instance/model.ckpt
  tokenizer_path: ./data/models/docred_joint/joint_multi_instance #./data/models/docred_joint/joint_multi_instance
  encoder_config_path: ./data/models/docred_joint/joint_multi_instance #./data/models/docred_joint/joint_multi_instance

inference:
  test_batch_size: 1
  max_spans: 200
  max_coref_pairs: null
  max_rel_pairs: 50

distribution:
  gpus: [0]
  accelerator: ''
  prepare_data_per_node: false

hydra:
  run:
    dir: ./data/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: run_config
